@startuml

skinparam roundcorner 5
skinparam shadowing false

skinparam ArrowColor #333333
skinparam BackgroundColor #ffffff

skinparam default {
    FontColor #333333
    FontName Arial
    FontSize 12
    MonospacedFontName Source Code Pro
}

skinparam Activity {
    ArrowColor #009dff
    BackgroundColor #f2faff
    BorderColor #009dff
    DiamondBackgroundColor #fffaff
}

skinparam Actor {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Boundary {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Control {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Entity {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Node {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Interface {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Usecase {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Rectangle {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Note {
    BackgroundColor #333333
    BorderColor #ffffff
    FontColor #ffffff
}

skinparam Package {
    BackgroundColor #fcfeff
    BorderColor #009dff
    BorderThickness .5
}

skinparam Class {
    ArrowColor #009dff
    BackgroundColor #f2faff
    BorderColor #009dff
    Linetype ortho
}

skinparam Queue {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Database {
    BackgroundColor #ffffff
    BorderColor #009dff
}

skinparam Participant {
    BackgroundColor #009dff
    BorderColor #009dff
    FontColor #ffffff
    FontStyle bold
}

skinparam State {
    BackgroundColor #ffffff
    BorderColor #009dff
    FontStyle bold
}

skinparam Sequence {
    LifeLineBorderColor #009dff
    MessageAlignment direction
}

@enduml
